### ISSUE TITLE
Feature: Devconainer

### ISSUE THREAD

**Issue by Arevalo-Edgar14** [Arevalo-Edgar14/IA2#2]
As a developer want a devcontainer to work with python and (vue or react) to work with reactiveness on the view side. and for reusable components as canvas2D

acceptance criteria:
  
  - [x] have python installed
  - [x] be able to install python packages
  - [x] be able to install js packages
  - [x] have js reactive library installed
  - [x] have linter for js reactive library
  - [x] have linter for python
  - [x] have python web application framework (flask or django) installed

**Comment by Erev14** [comment]
PR approved, clossing issue

**Comment by Erev14** [comment]
Js reactive library installed: Vue with CDN

**Comment by Erev14** [comment]
python flask web application framework

**Comment by Erev14** [comment]
Vue CDN is not ussable, Vue3 cli need to be installed instead

**Comment by Erev14** [comment]
Vue 3 cli remplace vue CDN on #23
